# Generated by Django 5.1.4 on 2024-12-10 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearup', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearup.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearup.product')),
            ],
        ),
    ]
